routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/base64', function(){
    $image = public_path('installer/img/pattern.png');;
    $img = \Image::make($image);
    return response()->make($img->encode($img->mime()), 200, array('Content-Type' => $img->mime(),'Cache-Control'=>'max-age=86400, public'));
});
# Employee Login
Route::get('/',['as'=>'front.login','uses'=>'front\LoginController@index']);
Route::post('/login',['as'=>'login','uses'=>'front\LoginController@ajaxLogin']);
Route::get('logout', ['as'=>'front.logout','uses'=>'front\LoginController@logout']);

# Employee Panel After Login
Route::group(['middleware' => ['auth.employees'],'namespace' => 'front'], function()
{
    Route::get('/change_password_modal',['as'=>'front.change_password_modal','uses'=>'DashboardController@changePasswordModal']);
    Route::post('/change_password',['as'=>'front.change_password','uses'=>'DashboardController@change_password']);
    Route::get('ajaxApplications',['as'=>'front.leave_applications','uses'=> 'DashboardController@ajaxApplications']);

    Route::get('leave',['as'=>'front.leave','uses'=>'DashboardController@leave']);

    Route::post('dashboard/notice/{id}',['as'=>'front.notice_ajax','uses'=>'DashboardController@notice_ajax']);

    Route::post('leave_store',['as'=>'front.leave_store','uses'=>'DashboardController@leave_store']);


    Route::resource('dashboard','DashboardController');
});
# Admin Login
Route::group([ 'middleware' => ['auth.employees'],'prefix' => 'admin','namespace' => 'Admin'], function() {
    Route::get('notice/{id}', ['as'=>'front.show_notice','uses'=>'NoticeboardsController@show']);
    Route::get('award/{id}', ['as'=>'front.show_award_details','uses'=>'AwardsController@show']);
});

# Admin Login
Route::group([ 'prefix' => 'admin','namespace' => 'Admin'], function()
{

    Route::get('/',['as'=>'admin.getlogin','uses'=>'AdminLoginController@index']);
    Route::get('logout',['as'=>'admin.logout','uses'=> 'AdminLoginController@logout']);

    Route::post('login',['as'=>'admin.login','uses'=> 'AdminLoginController@ajaxAdminLogin']);

});


// Admin Panel After Login
Route::group(['middleware' => ['auth.admin'], 'prefix' => 'admin','namespace' => 'Admin'], function()
{

    //	Dashboard Routing
    //Route::resource('dashboard', 'AdminDashboardController');
    Route::resource('dashboard', 'AdminDashboardController',['as' => 'admin']);

    //    Employees Routing
    Route::get('employees/export',['as'=>'admin.employees.export','uses'=>'EmployeesController@export']);
    Route::get('employees/employeeLogin/{id}',['as'=>'admin.employees.employeeLogin','uses'=>'EmployeesController@employeesLogin']);
    Route::get('employees/employeelist',['as'=>'admin.employees.ajaxlist','uses'=>'EmployeesController@ajaxEmployees']);
    Route::resource('employees', 'EmployeesController',['except' => ['show'],'as' => 'admin']);


    //  Awards Routing
    Route::get('ajax_awards/',['as'=>'admin.ajax_awards','uses'=> 'AwardsController@ajax_awards']);
    Route::resource('awards', 'AwardsController',['except'=>['show'],'as' => 'admin']);

    //  Department Routing
    Route::get('departments/ajax_designation/',['as'=>'admin.departments.ajax_designation','uses'=> 'DepartmentsController@ajax_designation']);
    Route::get('departments/ajax_department/',['as'=>'admin.departments.ajax_department','uses'=> 'DepartmentsController@ajaxDepartments']);
    Route::resource('departments', 'DepartmentsController',['as' => 'admin']);

    //    Expense Routing
    Route::get('ajax_expenses/',['as'=>'admin.ajax_expenses','uses'=> 'ExpensesController@ajax_expenses']);
    Route::resource('expenses', 'ExpensesController',['except' => ['show'],'as' => 'admin']);

    //    Holiday Routing
    Route::get('holidays/mark_sunday', 'HolidaysController@Sunday');
    Route::resource('holidays', 'HolidaysController',['as' => 'admin']);

    //  Routing for the attendance
    Route::get('attendances/report/{attendances}', ['as'=>'admin.attendance.report','uses'=>'AttendancesController@report']);
    Route::get('attendances/ajax-attendance-list', ['as'=>'admin.attendance.ajax-attendance-list','uses'=>'AttendancesController@ajaxAttendanceList']);
    Route::post('attendances/export', ['as'=>'admin.attendance.export','uses'=>'AttendancesController@export']);
    Route::resource('attendances', 'AttendancesController',['as' => 'admin']);

    //    Routing or the leavetypes
    Route::get('leavetypes/ajax_list',['as'=>'admin.leavetypes.ajax_list','uses'=> 'LeavetypesController@ajaxLeaveType']);
    Route::resource('leavetypes', 'LeavetypesController',['except'=>['show'],'as' => 'admin']);

    //    Leave Applications routing
    Route::get('leave_applications/ajaxApplications',['as'=>'admin.leave_applications','uses'=> 'LeaveApplicationsController@ajaxApplications']);
    Route::resource('leave_applications', 'LeaveApplicationsController',['except'=>['create','store','edit'],'as' => 'admin']);

    //   Routing for setting
    Route::resource('settings', 'SettingsController',['only'=>['edit','update'],'as' => 'admin']);

    //    Salary Routing
    Route::get('add-salary-modal/{employeeID}',['as'=>'admin.add-salary-modal','uses'=>  'SalaryController@addSalaryModal']);

    Route::resource('salary','SalaryController',['only'=>['destroy','show','update','store'],'as' => 'admin']);

    //    Profile Setting
    Route::resource('profile_settings', 'ProfileSettingsController',['only'=>['edit','update'],'as' => 'admin']);

    //   Notification Setting

    Route::post('ajax_update_notification',['as'=>'admin.ajax_update_notification','uses'=> 'NotificationSettingsController@ajax_update_notification']);
    Route::resource('notificationSettings', 'NotificationSettingsController',['only'=>['edit','update'],'as' => 'admin']);

    Route::post('ajax_update_email_setting',['as'=>'admin.ajax_update_email_setting','uses'=> 'EmailSettingsController@ajax_email_setting']);
    Route::resource('email_settings', 'EmailSettingsController',['only'=>['edit','update'],'as' => 'admin']);

    //  Notice Board
    Route::get('ajax_notices/',['as'=>'admin.ajax_notices','uses'=> 'NoticeboardsController@ajax_notices']);
    Route::resource('noticeboards', 'NoticeboardsController',['except'=>['show'],'as' => 'admin']);


    Route::get('update-new-version', ['as' => 'admin.updateVersion.index', 'uses' => 'AdminUpdateVersionController@index']);

    Route::resource('leave_settings', 'LeaveSettingsController', ['as' => 'admin']);

});
Event::listen('auth.login', function($user)
{
    $user->last_login = new DateTime;
    $user->save();
});
// Lock Screen Routing
Route::get('screenlock', 'Admin\AdminDashboardController@screenlock');

app/Http/Controllers/Admin/LeaveApplicationsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Classes\Reply;
use App\Events\LeaveRequestEvent;
use App\Http\Controllers\AdminBaseController;
use App\Http\Requests\Admin\LeaveApplication\IndexRequest;
use App\Http\Requests\Admin\LeaveApplication\UpdateRequest;
use App\Models\Attendance;
use App\Models\Employee;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\View;
use Yajra\DataTables\Facades\DataTables;

/**
 * Class LeaveApplicationsController
 * @package App\Http\Controllers\Admin
 */
class LeaveApplicationsController extends AdminBaseController
{

    public function __construct()
    {
        parent::__construct();
//        dd($this->setting);
        $this->leaveApplicationActive = 'active';
        $this->pageTitle = 'Leave Applications';
    }

    /**
     * @param IndexRequest $request
     * @return \Illuminate\Contracts\View\View
     */
    public function index(IndexRequest $request)
    {
        $this->leave_applications = Attendance::all();
        return View::make('admin.leave_applications.index', $this->data);
    }

    // Datatable ajax request

    /**
     * @return mixed
     */
    public function ajaxApplications()
    {
        $result = Attendance::select('attendance.id', 'employees.fullName', 'attendance.date', 'attendance.leaveType', 'attendance.reason', 'attendance.applied_on', 'attendance.application_status', 'attendance.halfDayType')
            ->join('employees', 'employees.employeeID', '=', 'attendance.employeeID')
            ->whereNotNull('attendance.application_status')
            ->orderBy('attendance.applied_on', 'desc');

        return DataTables::of($result)
            ->editColumn('date', function ($row) {
                return date('d-M-Y', strtotime($row->date));
            })
            ->editColumn('applied_on', function ($row) {
                return date('d-M-Y', strtotime($row->applied_on));
            })
            ->editColumn('leaveType', function ($row) {
                $leave = ($row->leaveType == 'half day') ? $row->leaveType . '-' . $row->halfDayType : $row->leaveType;
                return $leave;
            })
            ->editColumn('reason', function ($row) {
                return strip_tags(\Illuminate\Support\Str::limit($row->reason, 50));

            })
            ->editColumn('application_status', function ($row) {
                $color = [
                    'pending' => 'warning',
                    'approved' => 'success',
                    'rejected' => 'danger'
                ];

                return '<span class="label label-' . $color[$row->application_status] . '">' . $row->application_status . '</span>';
            })
            ->removeColumn('halfDayType')
            ->addColumn('edit', function ($row) {
                return '<p><button  class="btn btn-sm purple" onclick="show_application(' . $row->id . ');return false;" ><i class="fa fa-edit"></i> View/Edit</button></p>
                          <p><a style="width: 106px;" href="javascript:;" onclick="del(' . $row->id . ');return false;" class="btn btn-sm red">
                        <i class="fa fa-trash"></i> Delete</a></p>';
            })
            ->escapeColumns(['edit', 'application_status'])
            ->make(false);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\View
     */
    public function show($id)
    {
        $this->leave_application = Attendance::find($id);
        return View::make('admin.leave_applications.show', $this->data);
    }

    /**
     * @param UpdateRequest $request
     * @param $id
     * @return array
     */
    public function update(UpdateRequest $request, $id)
    {
        $this->updated_by = Auth::guard('admin')->user()->email;

        $leaveApplication = Attendance::findOrFail($id);
        $leaveApplication->application_status = $request->application_status;
        $leaveApplication->save();
        // Send Email to All active users
        $attendance = Attendance::find($id);

        $this->attendance = $attendance;
        $employee = Employee::where('employeeID', '=', $attendance->employeeID)->first();
        $this->email = $employee->email;

        if ($this->setting->leave_notification == 1) {
            if ($leaveApplication->application_status != 'pending') {
                // TODO: Mail Implementation
                $attendanceDate = date('d-M-Y', strtotime($this->attendance->date));
                event(new LeaveRequestEvent($employee, $attendanceDate, $leaveApplication->application_status));
            }
        }

        return Reply::success('Leave Request updated successfully');
    }

    /**
     * @param $id
     * @return array
     */
    public function destroy($id)
    {
        Attendance::destroy($id);
        return Reply::success('Deleted successfully');
    }

}

resources/views/admin/leave_applications/create.blade.php
/Users/Ajay/hrm/app/views/leave_applications/create.blade.php

resources/views/admin/leave_applications/edit.blade.php
edit

resources/views/admin/leave_applications/index.blade.php
@extends('admin.adminlayouts.adminlayout')

@section('head')
	<!-- BEGIN PAGE LEVEL STYLES -->
	{!! HTML::style("assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css") !!}
	<!-- END PAGE LEVEL STYLES -->

@stop


@section('mainarea')


			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			{{$pageTitle}}
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="{{route('admin.dashboard.index')}}">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">Leave Applications</a>
						<i class="fa "></i>
					</li>

				</ul>

			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN PAGE CONTENT-->
						<div class="row">
            				<div class="col-md-6">

                            </div>
            				<div class="col-md-6 form-group text-right">

            				<span id="load_notification"></span>
            					 <input  type="checkbox"  onchange="ToggleEmailNotification('leave_notification');return false;" class="make-switch" name="leave_notification" @if($setting->leave_notification==1)checked	@endif data-on-color="success" data-on-text="Yes" data-off-text="No" data-off-color="danger">
            					<strong>Email Notification</strong><br>


            				</div>
                         </div>

			<div class="row">
				<div class="col-md-12">

					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div id="load">

					  @include('admin.common.error')

					</div>
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-rocket"></i>Applications
							</div>
							<div class="tools">
							</div>
						</div>

						<div class="portlet-body">


							<table class="table table-striped table-bordered table-hover" id="applications">
                                     <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Date</th>
                                        <th>Leave Type</th>
                                        <th>Reason</th>
                                        <th>Applied on</th>
                                        <th>Status</th>
                                        <th>Action</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                         <td> {{-- ID from Contoller ajaxload------}} </td>
                                         <td> {{-- Name from Contoller ajaxload----}} </td>
                                         <td> {{-- Date from Contoller ajaxload----}} </td>
                                         <td> {{-- Leavetype from Contoller ajaxload--}} </td>
                                         <td> {{-- Reason from Contoller ajaxload----}} </td>
                                         <td> {{-- Applied on from Contoller ajaxload---}} </td>
                                         <td> {{-- Status from Contoller ajaxload----}} </td>
                                         <td> {{-- Action from Contoller ajaxload----}} </td>
                                    </tr>

                                        </tbody>

							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->

				</div>
			</div>
			<!-- END PAGE CONTENT-->


{{--Leave Application view MODALS--}}
{!! Form::open(['url'=>'','id'=>'edit_form_application','method'=>'PATCH']) !!}
<div id="leaveApplicationIndex" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <span class="caption-subject font-red-sunglo bold uppercase">Leave Application</span>
                    </div>
                    <div class="modal-body" id="modal-data-application">
                        {{--Ajax data call for form--}}
                    </div>
                </div>

            </div>
        </div>
</div>
{!! Form::close() !!}
{{--Leave Application view MODALS--}}

			{{--DELETE MODAL CALLING--}}
@include('admin.include.delete-modal')
@include('include.show-modal')
            {{--DELETE MODAL CALLING END--}}
@stop



@section('footerjs')


<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
	{!!  HTML::script("assets/global/plugins/select2/select2.min.js") !!}
	  {!! HTML::script("assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js") !!}
	{!!  HTML::script("assets/global/plugins/datatables/media/js/jquery.dataTables.min.js") !!}
	{!!  HTML::script("assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js") !!}
    {!!  HTML::script("assets/admin/pages/scripts/table-managed.js") !!}
<!-- END PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->

 <script>
        var table = $('#applications').dataTable( {
					"bProcessing": true,
					"bServerSide": true,
					"sAjaxSource": "{{ URL::route('admin.leave_applications') }}",
					"aaSorting": [[ 1, "asc" ]],
					"aoColumns": [
						{ 'sClass': 'center', "bSortable": true  },
						{ 'sClass' : 'center',  "bSortable": true },
						{ 'sClass': 'center', "bSortable": true },
						{ 'sClass': 'center', "bSortable": true },
						{ 'sClass': 'center', "bSortable": true },
						{ 'sClass': 'center', "bSortable": true },
						{ 'sClass': 'center', "bSortable": true },
						{ 'sClass': 'center', "bSortable": false }
					],
					"lengthMenu": [
									[5, 15, 20, -1],
									[5, 15, 20, "All"] // change per page values here
								],
					"sPaginationType": "full_numbers",
					"fnRowCallback": function( nRow, aData, iDisplayIndex ) {
						var row = $(nRow);
						row.attr("id", 'row'+aData['0']);
					}

        });
		// // Javascript function to update the company info and Bank Info
		function updateLeaveApplication(id){

			var url = "{{ route('admin.leave_applications.update',':id') }}";
			url = url.replace(':id',id);
			$.easyAjax({
				type: 'PUT',
				url: url,
				container: '#edit_form_application',
				data: $('#edit_form_application').serialize(),
				success: function () {
					$('#leaveApplicationIndex').modal('hide');
					table.fnDraw();
				}
			});
		}

		// Show Create Department Modal
		function show_application(id) {
			var url = "{{ route('admin.leave_applications.show',':id') }}";
			url = url.replace(':id',id);
			$.ajaxModal('#leaveApplicationIndex', url);
		}
		// Show Delete Modal
		function del(id) {

			$('#deleteModal').modal('show');

			$("#deleteModal").find('#info').html('Are you sure ! You want to delete ?');

			$('#deleteModal').find("#delete").off().click(function () {

				var url = "{{ route('admin.leave_applications.destroy',':id') }}";
				url = url.replace(':id',id);

				var token = "{{ csrf_token() }}";

				$.easyAjax({
					type: 'DELETE',
					url: url,
					data: {'_token': token},
					container: "#deleteModal",
					success: function (response) {
						if (response.status == "success") {
							$('#deleteModal').modal('hide');
							table.fnDraw();
						}
					}
				});

			});
		}

    </script>


@stop
	

resources/views/admin/leave_applications/show.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title"><strong>View Application</strong></h4>
</div>
<div class="modal-body">
    <input type="hidden" name="_method" value="PUT">
    <input type="hidden" name="_token" value="{{csrf_token()}}">
    <div class="portlet-body form">
        <div class="row">
            <label class="control-label col-md-3"><strong>Name</strong></label>
            <div class="col-md-9">
                {{$leave_application->employeeDetails->fullName}}
            </div>
        </div>
        <br>
        <div class="row">
            <label class="control-label col-md-3"><strong>Leave Type</strong></label>
            <div class="col-md-9">
                @if($leave_application->leaveType == 'half day')
                    {{ucfirst($leave_application->leaveType)}} - {{$leave_application->halfDayType}}
                @else
                    {{ucfirst($leave_application->leaveType)}}
                @endif
            </div>
        </div>
        <br>
        <div class="row">
            <label class="control-label col-md-3"><strong>Date</strong></label>
            <div class="col-md-9">
                {{date('d-M-Y',strtotime($leave_application->date))}}
            </div>
        </div>
        <br>
        <div class="row">
            <label class="control-label col-md-3"><strong>Reason</strong></label>
            <div class="col-md-9">
                {{$leave_application->reason}}
            </div>
        </div>
        <br>
        <div class="row">
            <label class="control-label col-md-3"><strong>Applied on</strong></label>
            <div class="col-md-9">
                {{date('d-M-Y',strtotime($leave_application->applied_on))}}
            </div>
        </div>
        <br>
        <div class="row">
            <label class="control-label col-md-3"><strong>Action</strong></label>
            <div class="col-md-9">
                {{ Form::select('application_status', [
                    'pending'   =>  'Pending',
                    'approved'  =>  'Approved',
                    'rejected'  =>   'Rejected'
                  ], $leave_application->application_status,['class' => 'form-control']) }}
            </div>
        </div>
        <br>
        <div class="form-actions">
            <div class="row">
                <div class="col-md-offset-3 col-md-9">
                    <button type="button" onclick="updateLeaveApplication({{$leave_application->id}})"   class="btn green"><i class="fa fa-check"></i> Submit</button>
                </div>
            </div>
        </div>

    </div>
</div>