routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/base64', function(){
    $image = public_path('installer/img/pattern.png');;
    $img = \Image::make($image);
    return response()->make($img->encode($img->mime()), 200, array('Content-Type' => $img->mime(),'Cache-Control'=>'max-age=86400, public'));
});
# Employee Login
Route::get('/',['as'=>'front.login','uses'=>'front\LoginController@index']);
Route::post('/login',['as'=>'login','uses'=>'front\LoginController@ajaxLogin']);
Route::get('logout', ['as'=>'front.logout','uses'=>'front\LoginController@logout']);

# Employee Panel After Login
Route::group(['middleware' => ['auth.employees'],'namespace' => 'front'], function()
{
    Route::get('/change_password_modal',['as'=>'front.change_password_modal','uses'=>'DashboardController@changePasswordModal']);
    Route::post('/change_password',['as'=>'front.change_password','uses'=>'DashboardController@change_password']);
    Route::get('ajaxApplications',['as'=>'front.leave_applications','uses'=> 'DashboardController@ajaxApplications']);

    Route::get('leave',['as'=>'front.leave','uses'=>'DashboardController@leave']);

    Route::post('dashboard/notice/{id}',['as'=>'front.notice_ajax','uses'=>'DashboardController@notice_ajax']);

    Route::post('leave_store',['as'=>'front.leave_store','uses'=>'DashboardController@leave_store']);


    Route::resource('dashboard','DashboardController');
});
# Admin Login
Route::group([ 'middleware' => ['auth.employees'],'prefix' => 'admin','namespace' => 'Admin'], function() {
    Route::get('notice/{id}', ['as'=>'front.show_notice','uses'=>'NoticeboardsController@show']);
    Route::get('award/{id}', ['as'=>'front.show_award_details','uses'=>'AwardsController@show']);
});

# Admin Login
Route::group([ 'prefix' => 'admin','namespace' => 'Admin'], function()
{

    Route::get('/',['as'=>'admin.getlogin','uses'=>'AdminLoginController@index']);
    Route::get('logout',['as'=>'admin.logout','uses'=> 'AdminLoginController@logout']);

    Route::post('login',['as'=>'admin.login','uses'=> 'AdminLoginController@ajaxAdminLogin']);

});


// Admin Panel After Login
Route::group(['middleware' => ['auth.admin'], 'prefix' => 'admin','namespace' => 'Admin'], function()
{

    //	Dashboard Routing
    //Route::resource('dashboard', 'AdminDashboardController');
    Route::resource('dashboard', 'AdminDashboardController',['as' => 'admin']);

    //    Employees Routing
    Route::get('employees/export',['as'=>'admin.employees.export','uses'=>'EmployeesController@export']);
    Route::get('employees/employeeLogin/{id}',['as'=>'admin.employees.employeeLogin','uses'=>'EmployeesController@employeesLogin']);
    Route::get('employees/employeelist',['as'=>'admin.employees.ajaxlist','uses'=>'EmployeesController@ajaxEmployees']);
    Route::resource('employees', 'EmployeesController',['except' => ['show'],'as' => 'admin']);


    //  Awards Routing
    Route::get('ajax_awards/',['as'=>'admin.ajax_awards','uses'=> 'AwardsController@ajax_awards']);
    Route::resource('awards', 'AwardsController',['except'=>['show'],'as' => 'admin']);

    //  Department Routing
    Route::get('departments/ajax_designation/',['as'=>'admin.departments.ajax_designation','uses'=> 'DepartmentsController@ajax_designation']);
    Route::get('departments/ajax_department/',['as'=>'admin.departments.ajax_department','uses'=> 'DepartmentsController@ajaxDepartments']);
    Route::resource('departments', 'DepartmentsController',['as' => 'admin']);

    //    Expense Routing
    Route::get('ajax_expenses/',['as'=>'admin.ajax_expenses','uses'=> 'ExpensesController@ajax_expenses']);
    Route::resource('expenses', 'ExpensesController',['except' => ['show'],'as' => 'admin']);

    //    Holiday Routing
    Route::get('holidays/mark_sunday', 'HolidaysController@Sunday');
    Route::resource('holidays', 'HolidaysController',['as' => 'admin']);

    //  Routing for the attendance
    Route::get('attendances/report/{attendances}', ['as'=>'admin.attendance.report','uses'=>'AttendancesController@report']);
    Route::get('attendances/ajax-attendance-list', ['as'=>'admin.attendance.ajax-attendance-list','uses'=>'AttendancesController@ajaxAttendanceList']);
    Route::post('attendances/export', ['as'=>'admin.attendance.export','uses'=>'AttendancesController@export']);
    Route::resource('attendances', 'AttendancesController',['as' => 'admin']);

    //    Routing or the leavetypes
    Route::get('leavetypes/ajax_list',['as'=>'admin.leavetypes.ajax_list','uses'=> 'LeavetypesController@ajaxLeaveType']);
    Route::resource('leavetypes', 'LeavetypesController',['except'=>['show'],'as' => 'admin']);

    //    Leave Applications routing
    Route::get('leave_applications/ajaxApplications',['as'=>'admin.leave_applications','uses'=> 'LeaveApplicationsController@ajaxApplications']);
    Route::resource('leave_applications', 'LeaveApplicationsController',['except'=>['create','store','edit'],'as' => 'admin']);

    //   Routing for setting
    Route::resource('settings', 'SettingsController',['only'=>['edit','update'],'as' => 'admin']);

    //    Salary Routing
    Route::get('add-salary-modal/{employeeID}',['as'=>'admin.add-salary-modal','uses'=>  'SalaryController@addSalaryModal']);

    Route::resource('salary','SalaryController',['only'=>['destroy','show','update','store'],'as' => 'admin']);

    //    Profile Setting
    Route::resource('profile_settings', 'ProfileSettingsController',['only'=>['edit','update'],'as' => 'admin']);

    //   Notification Setting

    Route::post('ajax_update_notification',['as'=>'admin.ajax_update_notification','uses'=> 'NotificationSettingsController@ajax_update_notification']);
    Route::resource('notificationSettings', 'NotificationSettingsController',['only'=>['edit','update'],'as' => 'admin']);

    Route::post('ajax_update_email_setting',['as'=>'admin.ajax_update_email_setting','uses'=> 'EmailSettingsController@ajax_email_setting']);
    Route::resource('email_settings', 'EmailSettingsController',['only'=>['edit','update'],'as' => 'admin']);

    //  Notice Board
    Route::get('ajax_notices/',['as'=>'admin.ajax_notices','uses'=> 'NoticeboardsController@ajax_notices']);
    Route::resource('noticeboards', 'NoticeboardsController',['except'=>['show'],'as' => 'admin']);


    Route::get('update-new-version', ['as' => 'admin.updateVersion.index', 'uses' => 'AdminUpdateVersionController@index']);

    Route::resource('leave_settings', 'LeaveSettingsController', ['as' => 'admin']);

});
Event::listen('auth.login', function($user)
{
    $user->last_login = new DateTime;
    $user->save();
});
// Lock Screen Routing
Route::get('screenlock', 'Admin\AdminDashboardController@screenlock');

app/Http/Controllers/Admin/ProfileSettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Classes\Reply;
use App\Http\Controllers\AdminBaseController;
use App\Http\Requests\Admin\Profile\EditRequest;
use App\Http\Requests\Admin\Profile\UpdateRequest;
use App\Models\Admin;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\View;

/**
 * Class ProfileSettingsController
 * @package App\Http\Controllers\Admin
 */
class ProfileSettingsController extends AdminBaseController
{

    public function __construct()
    {
        parent::__construct();
        $this->settingOpen = 'active open';
        $this->pageTitle = 'Settings';
    }

    /**
     * Show the form for editing the specified Admin.
     */
    public function edit(EditRequest $request)
    {
        $this->admin = Admin::find(Auth::guard('admin')->user()->id);
        $this->profileSettingActive = 'active';

        return View::make('admin.profile_settings.edit', $this->data);
    }

    /**
     * @param UpdateRequest $request
     * @param $id
     * @return array
     */
    public function update(UpdateRequest $request, $id)
    {
        $admin = Admin::findOrFail(Auth::guard('admin')->user()->id);

        // Name and email change
        if ($request->type == 'name') {
            $admin->name = $request->name;
            $admin->email = $request->email;
        } else {
            $admin->password = Hash::make($request->password);
        }

        $admin->save();

        return Reply::success('Profile detail updated successfully');
    }

}

resources/views/admin/profile_settings/edit.blade.php
@extends('admin.adminlayouts.adminlayout')

@section('head')

    <!-- BEGIN PAGE LEVEL STYLES -->
    {!!  HTML::style("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css")  !!}
    {!!  HTML::style("assets/global/plugins/bootstrap-select/bootstrap-select.min.css")  !!}
    {!!  HTML::style("assets/global/plugins/select2/select2.css")  !!}
    {!!  HTML::style("assets/global/plugins/jquery-multi-select/css/multi-select.css")  !!}

    <!-- BEGIN THEME STYLES -->
@stop


@section('mainarea')

			
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			    {{$pageTitle}}
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="{{route('admin.dashboard.index')}}">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="{{ route('admin.notificationSettings.edit',$admin->id) }}">Settings</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href=""> Setting</a>
					</li>
				</ul>
			
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN PAGE CONTENT-->
			<div class="row">
				<div class="col-md-12">
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-cog"></i>Login Details {{$pageTitle}}
							</div>
							<div class="tools">
							</div>
						</div>

						<div class="portlet-body form">

						<!------------------------ BEGIN FORM---------------------->
						{!!  Form::model($admin, ['method' => 'PUT', 'id'=> 'update_profile_form','class'=>'form-horizontal form-bordered'])  !!}

                                    <div class="form-body">
                                        <div class="form-group">
                                        <label class="col-md-2 control-label">Name: <span class="required">
                                        * </span>
                                            </label>
                                            <div class="col-md-6 form-group">
                                                <input type="text" class="form-control" name="name" placeholder="Administrator Name" value="{{ $admin->name }}">
                                                <input type="hidden" name="type" value="name">
                                            </div>
                                        </div>

                                        <div class="form-group">
                                        <label class="col-md-2 control-label">Login Email: <span class="required">
                                            * </span>
                                            </label>
                                            <div class="col-md-6 form-group">
                                                <input type="text" class="form-control" name="email" placeholder="Email" value="{{ $admin->email}}" >
                                            </div>
                                        </div>
                                            <div class="form-actions">
                                                <div class="row">
                                                    <div class="col-md-offset-3 col-md-9">
                                                        <button type="button" onclick="updateProfile({{$admin->id}}, 'update_profile_form');return false;"   class="btn green"><i class="fa fa-check"></i> Submit</button>

                                                    </div>
                                                </div>
                                            </div>
                        						{!!  Form::close()  !!}
                       <!------------------------- END FORM ----------------------->

						</div>
					    </div>
					<!-- END EXAMPLE TABLE PORTLET-->
					
				    </div>
				                <div class="portlet box blue">
                						<div class="portlet-title">
                							<div class="caption">
                								<i class="fa fa-key"></i>Change Password
                							</div>
                							<div class="tools">
                							</div>
                						</div>

                						<div class="portlet-body form">

                						<!------------------------ BEGIN FORM Change Password---------------------->
                						{!!  Form::model($admin, ['method' => 'PUT','id'=> 'update_password_form', 'class'=>'form-horizontal form-bordered'])  !!}

                                                    <div class="form-body">

                                                        <div class="form-group">
                                                        <label class="col-md-2 control-label">Password: <span class="required">
                                                        * </span>
                                                            </label>
                                                            <div class="col-md-6 form-group">
                                                                <input type="password" class="form-control" name="password" placeholder="Password" >
                                                                <input type="hidden" name="type" value="password">
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                        <label class="col-md-2 control-label">Confirm password: <span class="required">
                                                            * </span>
                                                            </label>
                                                            <div class="col-md-6 form-group">
                                                                <input type="password" class="form-control" name="password_confirmation" placeholder="Confirm Password" >
                                                            </div>
                                                        </div>
                                                            <div class="form-actions">
                                                                <div class="row">
                                                                    <div class="col-md-offset-3 col-md-9">
                                                                        <button type="button" onclick="updateProfile({{$admin->id}}, 'update_password_form');return false;"   class="btn green"><i class="fa fa-check"></i> Submit</button>

                                                                    </div>
                                                                </div>
                                                            </div>
                                                    {!!  Form::close()  !!}
                                       <!------------------------- END FORM Change Password ----------------------->

                						</div>
                					</div>
                					<!-- END EXAMPLE TABLE PORTLET-->

                				</div>
			</div>
			<!-- END PAGE CONTENT-->



@stop

@section('footerjs')

<!-- BEGIN PAGE LEVEL PLUGINS -->
{!!  HTML::script("assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js")  !!}
{!!  HTML::script('assets/global/plugins/bootstrap-select/bootstrap-select.min.js')  !!}

{!!  HTML::script('assets/global/plugins/select2/select2.min.js')  !!}
{!!  HTML::script('assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js')  !!}
{!!  HTML::script('assets/admin/pages/scripts/components-dropdowns.js')  !!}



<script>
        jQuery(document).ready(function() {

           ComponentsDropdowns.init();
        });
        function updateProfile(id,div){
            var divID = '#'+div;
            var url = "{{ route('admin.profile_settings.update',':id') }}";
            url = url.replace(':id',id);
            $.easyAjax({
                type: 'POST',
                url: url,
                container: divID,
                data: $(divID).serialize(),
            });
        }
    </script>
<!-- END PAGE LEVEL PLUGINS -->
@stop