routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/base64', function(){
    $image = public_path('installer/img/pattern.png');;
    $img = \Image::make($image);
    return response()->make($img->encode($img->mime()), 200, array('Content-Type' => $img->mime(),'Cache-Control'=>'max-age=86400, public'));
});
# Employee Login
Route::get('/',['as'=>'front.login','uses'=>'front\LoginController@index']);
Route::post('/login',['as'=>'login','uses'=>'front\LoginController@ajaxLogin']);
Route::get('logout', ['as'=>'front.logout','uses'=>'front\LoginController@logout']);

# Employee Panel After Login
Route::group(['middleware' => ['auth.employees'],'namespace' => 'front'], function()
{
    Route::get('/change_password_modal',['as'=>'front.change_password_modal','uses'=>'DashboardController@changePasswordModal']);
    Route::post('/change_password',['as'=>'front.change_password','uses'=>'DashboardController@change_password']);
    Route::get('ajaxApplications',['as'=>'front.leave_applications','uses'=> 'DashboardController@ajaxApplications']);

    Route::get('leave',['as'=>'front.leave','uses'=>'DashboardController@leave']);

    Route::post('dashboard/notice/{id}',['as'=>'front.notice_ajax','uses'=>'DashboardController@notice_ajax']);

    Route::post('leave_store',['as'=>'front.leave_store','uses'=>'DashboardController@leave_store']);


    Route::resource('dashboard','DashboardController');
});
# Admin Login
Route::group([ 'middleware' => ['auth.employees'],'prefix' => 'admin','namespace' => 'Admin'], function() {
    Route::get('notice/{id}', ['as'=>'front.show_notice','uses'=>'NoticeboardsController@show']);
    Route::get('award/{id}', ['as'=>'front.show_award_details','uses'=>'AwardsController@show']);
});

# Admin Login
Route::group([ 'prefix' => 'admin','namespace' => 'Admin'], function()
{

    Route::get('/',['as'=>'admin.getlogin','uses'=>'AdminLoginController@index']);
    Route::get('logout',['as'=>'admin.logout','uses'=> 'AdminLoginController@logout']);

    Route::post('login',['as'=>'admin.login','uses'=> 'AdminLoginController@ajaxAdminLogin']);

});


// Admin Panel After Login
Route::group(['middleware' => ['auth.admin'], 'prefix' => 'admin','namespace' => 'Admin'], function()
{

    //	Dashboard Routing
    //Route::resource('dashboard', 'AdminDashboardController');
    Route::resource('dashboard', 'AdminDashboardController',['as' => 'admin']);

    //    Employees Routing
    Route::get('employees/export',['as'=>'admin.employees.export','uses'=>'EmployeesController@export']);
    Route::get('employees/employeeLogin/{id}',['as'=>'admin.employees.employeeLogin','uses'=>'EmployeesController@employeesLogin']);
    Route::get('employees/employeelist',['as'=>'admin.employees.ajaxlist','uses'=>'EmployeesController@ajaxEmployees']);
    Route::resource('employees', 'EmployeesController',['except' => ['show'],'as' => 'admin']);


    //  Awards Routing
    Route::get('ajax_awards/',['as'=>'admin.ajax_awards','uses'=> 'AwardsController@ajax_awards']);
    Route::resource('awards', 'AwardsController',['except'=>['show'],'as' => 'admin']);

    //  Department Routing
    Route::get('departments/ajax_designation/',['as'=>'admin.departments.ajax_designation','uses'=> 'DepartmentsController@ajax_designation']);
    Route::get('departments/ajax_department/',['as'=>'admin.departments.ajax_department','uses'=> 'DepartmentsController@ajaxDepartments']);
    Route::resource('departments', 'DepartmentsController',['as' => 'admin']);

    //    Expense Routing
    Route::get('ajax_expenses/',['as'=>'admin.ajax_expenses','uses'=> 'ExpensesController@ajax_expenses']);
    Route::resource('expenses', 'ExpensesController',['except' => ['show'],'as' => 'admin']);

    //    Holiday Routing
    Route::get('holidays/mark_sunday', 'HolidaysController@Sunday');
    Route::resource('holidays', 'HolidaysController',['as' => 'admin']);

    //  Routing for the attendance
    Route::get('attendances/report/{attendances}', ['as'=>'admin.attendance.report','uses'=>'AttendancesController@report']);
    Route::get('attendances/ajax-attendance-list', ['as'=>'admin.attendance.ajax-attendance-list','uses'=>'AttendancesController@ajaxAttendanceList']);
    Route::post('attendances/export', ['as'=>'admin.attendance.export','uses'=>'AttendancesController@export']);
    Route::resource('attendances', 'AttendancesController',['as' => 'admin']);

    //    Routing or the leavetypes
    Route::get('leavetypes/ajax_list',['as'=>'admin.leavetypes.ajax_list','uses'=> 'LeavetypesController@ajaxLeaveType']);
    Route::resource('leavetypes', 'LeavetypesController',['except'=>['show'],'as' => 'admin']);

    //    Leave Applications routing
    Route::get('leave_applications/ajaxApplications',['as'=>'admin.leave_applications','uses'=> 'LeaveApplicationsController@ajaxApplications']);
    Route::resource('leave_applications', 'LeaveApplicationsController',['except'=>['create','store','edit'],'as' => 'admin']);

    //   Routing for setting
    Route::resource('settings', 'SettingsController',['only'=>['edit','update'],'as' => 'admin']);

    //    Salary Routing
    Route::get('add-salary-modal/{employeeID}',['as'=>'admin.add-salary-modal','uses'=>  'SalaryController@addSalaryModal']);

    Route::resource('salary','SalaryController',['only'=>['destroy','show','update','store'],'as' => 'admin']);

    //    Profile Setting
    Route::resource('profile_settings', 'ProfileSettingsController',['only'=>['edit','update'],'as' => 'admin']);

    //   Notification Setting

    Route::post('ajax_update_notification',['as'=>'admin.ajax_update_notification','uses'=> 'NotificationSettingsController@ajax_update_notification']);
    Route::resource('notificationSettings', 'NotificationSettingsController',['only'=>['edit','update'],'as' => 'admin']);

    Route::post('ajax_update_email_setting',['as'=>'admin.ajax_update_email_setting','uses'=> 'EmailSettingsController@ajax_email_setting']);
    Route::resource('email_settings', 'EmailSettingsController',['only'=>['edit','update'],'as' => 'admin']);

    //  Notice Board
    Route::get('ajax_notices/',['as'=>'admin.ajax_notices','uses'=> 'NoticeboardsController@ajax_notices']);
    Route::resource('noticeboards', 'NoticeboardsController',['except'=>['show'],'as' => 'admin']);


    Route::get('update-new-version', ['as' => 'admin.updateVersion.index', 'uses' => 'AdminUpdateVersionController@index']);

    Route::resource('leave_settings', 'LeaveSettingsController', ['as' => 'admin']);

});
Event::listen('auth.login', function($user)
{
    $user->last_login = new DateTime;
    $user->save();
});
// Lock Screen Routing
Route::get('screenlock', 'Admin\AdminDashboardController@screenlock');

resources/views/admin/include/delete-modal.blade.php
<!-- Start - Delete Modal -->
<div id="deleteModal" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="deleteUserModalForm">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Delete ?</h4>
            </div>
            <div class="modal-body" id="info">

            </div>
            <div class="modal-footer">
                <button class="btn btn-default dark " data-dismiss="modal" aria-hidden="true">Close</button>
                <button id="delete" class="btn btn-sm red">Delete</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/include/footer.blade.php
<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div class="page-footer-inner">
		 {{date('Y')}} &copy; {{$setting->website}}
	</div>
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>
<!-- END FOOTER -->

resources/views/admin/include/footerjs.blade.php
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>

{!!  HTML::script("assets/global/plugins/respond.min.js")  !!}
{!!  HTML::script("assets/global/plugins/excanvas.min.js")  !!}

<![endif]-->
{!!  HTML::script("assets/global/plugins/jquery.min.js")  !!}
{!!  HTML::script("assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js")  !!}
{!!  HTML::script("assets/global/plugins/bootstrap/js/bootstrap.min.js")  !!}
{!!  HTML::script("assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js")  !!}
{!!  HTML::script("assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js")  !!}
{!! HTML::script('assets/global/plugins/froiden-helper/helper.js') !!}

{!!  HTML::script("assets/global/scripts/metronic.js") !!}
{!!  HTML::script("assets/admin/layout/scripts/layout.js") !!}


<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function () {
        Metronic.init(); // init metronic core componets
        Layout.init(); // init layout
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $('.demo-loading-btn')
            .click(function () {
                var btn = $(this)
                btn.button('loading')
                setTimeout(function () {
                    btn.button('reset')
                }, 8000)
            });
        $('.demo-loading-btn-ajax')
            .click(function () {
                var btn = $(this)
                btn.button('loading')
                setTimeout(function () {
                    btn.button('reset')
                }, 500)
            });


    });

    function ToggleEmailNotification(type) {
        if ($('[name=' + type + ']').is(':checked')) {
            var value = 1;
        }
        else {
            var value = 0;
        }
        <!--$('#load_notification').html('<img src="{{$setting->getLogoImageAttribute()}}" height="30px" width="117px" />');-->

        var url = "{{route('admin.ajax_update_notification')}}";

        $.easyAjax({
            type: 'POST',
            url: url,
            container: '#load_notification',
            data: {'value': value, 'id': '{{ $setting->id}}', 'type': type},
            success: function (response) {
                if (response.success == 'success') {
                    $('#load_notification').html('');
                }
            }
        });

    }

    function updateLeaveApplication(id) {

        var url = "{{route('admin.leave_applications.update',':id')}}";
        url = url.replace(':id', id);

        $.easyAjax({
            type: 'PUT',
            url: url,
            container: '#edit_form_leave',
            data: $('#edit_form_leave').serialize(),
            success: function () {
                window.location.reload();
            }
        });

    }
</script>

@yield('footerjs')

resources/views/admin/include/head.blade.php
<meta charset="utf-8"/>
<title>{{$setting->website}} - {{ $pageTitle }}</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta name="csrf-token" content="{{ csrf_token() }}"/>

<!-- BEGIN GLOBAL MANDATORY STYLES -->
{!! HTML::style("https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all")!!}
{!! HTML::style("assets/global/plugins/font-awesome/css/font-awesome.min.css") !!}
{!! HTML::style("assets/global/plugins/simple-line-icons/simple-line-icons.min.css") !!}
{!! HTML::style("assets/global/plugins/bootstrap/css/bootstrap.min.css") !!}
{!! HTML::style("assets/global/plugins/uniform/css/uniform.default.css") !!}
{!! HTML::style("assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css") !!}

@yield('head')

{!! HTML::style("assets/global/css/components.css") !!}
{!! HTML::style("assets/global/css/plugins.css") !!}
{!! HTML::style("assets/admin/layout/css/layout.css") !!}
{!! HTML::style("assets/admin/layout/css/themes/darkblue.css") !!}
{!! HTML::style("assets/admin/layout/css/custom.css") !!}
{!! HTML::style('assets/global/plugins/froiden-helper/helper.css')  !!}

resources/views/admin/include/header.blade.php
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="javascript:;">
                <img src="{{$setting->getLogoImageAttribute()}}" height="30px" />

            </a>
            <div class="menu-toggler sidebar-toggler hide">
                <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
            </div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse"
           data-target=".navbar-collapse">
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">

                <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                       data-close-others="true">
                        <i class="icon-bell"></i>

                        @if(count($pending_applications)>0)
                            <span class="badge badge-default">
											{{count($pending_applications)}}
										</span>
                        @endif

                    </a>


                    <ul class="dropdown-menu">
                        <li class="external">
                            <h3><span class="bold">{{count($pending_applications)}} pending</span> notifications</h3>

                        </li>
                        @if(count($pending_applications)>0)
                            <li>
                                <ul class="dropdown-menu-list scroller" style="height: 250px;"
                                    data-handle-color="#637283">
                                    @foreach($pending_applications as $pending)
                                        <li>
                                            <a data-toggle="modal" href="#static_leave_requests"
                                               onclick="show_application_notification({{ $pending->id }});return false;">
                                                <span class="time">{{date('d-M-Y',strtotime($pending->created_at))}}</span>
                                                <span class="details">
                									<span class="label label-sm label-icon label-success">
                									<i class="fa fa-bell-o"></i>
                									</span>
                									 <strong>{{$pending->employeeDetails->fullName}} </strong> has applied for leave on {{date('d-M-Y',strtotime($pending->date))}}</span>
                                            </a>
                                        </li>
                                    @endforeach

                                </ul>
                            </li>
                        @endif
                    </ul>
                </li>

                <li class="dropdown dropdown-user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                       data-close-others="true">

                    <span class="username username-hide-on-mobile">
                  {{ $loggedAdmin->name }}</span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <li>
                            <a href="{{route('admin.profile_settings.edit',Auth::guard('admin')->user()->id)}}">
                                <i class="icon-user"></i> My Profile </a>
                        </li>

                        <li class="divider">
                        </li>
                        <li>
                            <a href="{{ URL::to('screenlock') }} ">
                                <i class="icon-lock"></i> Lock Screen </a>
                        </li>
                        <li>
                            <a href="{{ URL::route('admin.logout') }} " id="logout-form">
                                <i class="icon-logout"></i> Log Out </a>
                        </li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->

            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->


{{--Leave Application view MODALS--}}
{!! Form::open(['url'=>'','id'=>'edit_form_leave','method'=>'PATCH']) !!}
<div id="static_leave_requests" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <span class="caption-subject font-red-sunglo bold uppercase">Leave Application</span>
            </div>
            <div class="modal-body" id="modal-data-leave">
                {{--Ajax data call for form--}}
            </div>
        </div>

    </div>
</div>
</div>
{!! Form::close() !!}
{{--Leave Modal Close--}}

<script>
    function show_application_notification(id) {
        $("#modal-data-leave").html('<div class="text-center">{!! HTML::image('assets/admin/layout/img/loading-spinner-blue.gif') !!}</div>');
        var editUrl = "{{ route('admin.leave_applications.update',[':id']) }}";
        editUrl = editUrl.replace(':id', id);
        $('#edit_form_leave').attr('action', editUrl);

        var url = "{{ route('admin.leave_applications.show',[':id']) }}";
        url = url.replace(':id', id);
        $('#edit_form_leave').attr('action', url);

        $.ajax({
            type: "GET",
            url: url

        }).done(function (response) {
            $('#modal-data-leave').html(response);
//
        });
    }
</script>

resources/views/admin/include/sidebar.blade.php
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
        <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
        <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
        <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
            <li class="sidebar-toggler-wrapper">
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                <div class="sidebar-toggler">
                </div>
                <!-- END SIDEBAR TOGGLER BUTTON -->
            </li>


            {{---------------------------------------Dashboard-------------------------------}}
            <li class="start {{ $dashboardActive ?? ''}}">
                <a href="{{URL::to('admin')}}">
                    <i class="fa fa-home"></i>
                    <span class="title">{!! Lang::get('menu.dashboard') !!}</span>
                    <span class="selected"></span>
                </a>
            </li>
            {{---------------------------------------/Dashboard-------------------------------}}


            {{---------------------------------------Employees-------------------------------}}
            <li class="{{ $employeesActive ?? ''}}">
                <a href="{{route('admin.employees.index')}}">
                    <i class="fa fa-users"></i>
                    <span class="title">{!! Lang::get('menu.employees') !!}</span>
                </a>
            </li>
            {{---------------------------------------/Employees-------------------------------}}


            {{---------------------------------------Department-------------------------------}}
            <li class="{{ $departmentActive ?? ''}}">
                <a href="{{route('admin.departments.index')}}">
                    <i class="fa fa-briefcase"></i>
                    <span class="title">{!! Lang::get('menu.department') !!}</span>
                </a>
            </li>
            {{---------------------------------------Settings-------------------------------}}

            {{---------------------------------------Awards-------------------------------}}
            <!--
            <li class="{{ $awardsActive ?? ''}}">
                <a href="{{route('admin.awards.index')}}">
                    <i class="fa fa-trophy"></i>
                    <span class="title">{!! Lang::get('menu.award') !!}</span>
                </a>
            </li>
            -->
            {{---------------------------------------/Awards-------------------------------}}


            {{---------------------------------------Expense-------------------------------}}
            <!--
            <li class="{{ $inventoryActive ?? ''}}">
                <a href="{{route('admin.expenses.index')}}">
                    <i class="fa fa-money"></i>
                    <span class="title">{!! Lang::get('menu.expense') !!}</span>
                </a>
            </li>
            -->
            {{---------------------------------------/Expense-------------------------------}}


            {{---------------------------------------Holidays-------------------------------}}
            <li class="{{ $holidayActive ?? ''}}">
                <a href="{{route('admin.holidays.index')}}">
                    <i class="fa fa-send"></i>
                    <span class="title">{!! Lang::get('menu.holiday') !!}</span>
                </a>
            </li>
            {{---------------------------------------/Holiday-------------------------------}}


            {{---------------------------------------Attendance-------------------------------}}
            <li class="{{ $attendanceOpen ?? ''}}">
                <a href="javascript:;">
                    <i class="fa fa-user"></i>
                    <span class="title">{!! Lang::get('menu.attendance') !!}</span>
                    <span class="arrow "></span>
                </a>
                <ul class="sub-menu">
                    <li class="{{ $markAttendanceActive ?? ''}}">
                        <a href="{{route('admin.attendances.create')}}">
                            <i class="fa  fa-check"></i>
                            Mark Attendance</a>
                    </li>
                    <li class="{{ $viewAttendanceActive ?? ''}}">
                        <a href="{{route('admin.attendances.index')}}">
                            <i class="fa  fa-eye"></i>
                            {!! Lang::get('menu.viewAttendance') !!}</a>
                    </li>
                    <li class="{{ $leaveTypeActive ?? ''}}">
                        <a href="{{route('admin.leavetypes.index')}}">
                            <i class="fa fa-sitemap"></i>
                            {!! Lang::get('menu.leaveTypes') !!}</a>
                    </li>
                    {{-- <li class="{{ $leaveSettingActive ?? ''}}">
                        <a href="{{route('admin.leave_settings.index')}}">
                            <i class="fa fa-bell"></i>
                            {!! Lang::get('menu.leaveSetting') !!}</a>
                    </li> --}}
                </ul>
            </li>

            {{---------------------------------------/Attendance-------------------------------}}

            {{---------------------------------------Leave Applications-------------------------------}}
            <li class="{{ $leaveApplicationActive ?? ''}}">
                <a href="{{route('admin.leave_applications.index')}}">
                    <i class="fa fa-rocket"></i>
                    <span class="title">{!! Lang::get('menu.leaveApplication') !!}</span>
                </a>
            </li>

            {{---------------------------------------/Attendance-------------------------------}}


            {{---------------------------------------Notice Board-------------------------------}}
            <li class="{{ $noticeBoardActive ?? ''}}">
                <a href="{{route('admin.noticeboards.index')}}">
                    <i class="fa fa-clipboard"></i>
                    <span class="title">{!! Lang::get('menu.noticeBoard') !!}</span>
                </a>
            </li>

            {{---------------------------------------/Notice Board-------------------------------}}


            {{---------------------------------------Settings-------------------------------}}
            <li class="{{ $settingOpen ?? ''}}">
                <a href="javascript:;">
                    <i class="fa fa-cogs"></i>
                    <span class="title">{!! Lang::get('menu.settings') !!}</span>
                    <span class="arrow "></span>
                </a>
                <ul class="sub-menu">
                    <li class="{{ $settingActive ?? ''}}">
                        <a href="{{route('admin.settings.edit','setting')}}">
                            <i class="fa  fa-cog"></i>
                            {!! Lang::get('menu.generalSetting') !!}</a>
                    </li>

                    <li class="{{ $profileSettingActive ?? ''}}">
                        <a href="{{route('admin.profile_settings.edit','setting')}}">
                            <i class="fa fa-user"></i>
                            {!! Lang::get('menu.profileSetting') !!}</a>
                    </li>
                    <li class="{{ $notificationSettingActive ?? ''}}">
                        <a href="{{route('admin.notificationSettings.edit','setting')}}">
                            <i class="fa fa-bell"></i>
                            {!! Lang::get('menu.notificationSetting') !!}</a>
                    </li>

                    <li class="{{ $emailSettingActive ?? ''}}">
                        <a href="{{route('admin.email_settings.edit','setting')}}">
                            <i class="fa fa-bell"></i>
                            {!! Lang::get('menu.emailSetting') !!}</a>
                    </li>
                    <!--
                    <li class="{{ $updateSettingActive ?? ''}}">
                        <a href="{{route('admin.updateVersion.index')}}">
                            <i class="fa fa-language"></i>
                            {!! __('menu.updateLog') !!}</a>
                    </li>
                    -->
                </ul>
            </li>

            {{---------------------------------------/Settings-------------------------------}}

        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
</div>
<!-- END SIDEBAR -->